import type {
  ImportedChildBirthday,
  ImportedIrmaoBirthday,
  ImportedSpouseBirthday,
} from '@vl6/domain';

/**
 * Transcrito do relatório "Aniversário de Irmãos/cunhadas/familiares em
 * todos os meses" (GLEG, emitido 14/09/2026 10:04, Verdadeira Luz nº 06) —
 * PDF fornecido pelo Administrador. Cada Irmão traz dia/mês + idade
 * completada na emissão (nunca o ano — ver `computeBirthYear`); cônjuges e
 * filhos só trazem dia/mês, o relatório de origem nunca informa o ano
 * deles. Vínculo com o cadastro existente é feito pelo nome (normalizado,
 * sem acento/maiúscula) em `ImportBirthdayDataUseCase` — nunca por ID, o
 * relatório não tem nenhum identificador em comum com o Portal.
 */
export const BIRTHDAY_REPORT_DATE = new Date(2026, 8, 14);

export const IMPORTED_IRMAOS: ImportedIrmaoBirthday[] = [
  { nomeCompleto: 'Aldo Luis Silva Pereira', dia: 1, mes: 1, anos: 43 },
  { nomeCompleto: 'Helton José Chacarosque da Silva', dia: 6, mes: 1, anos: 44 },
  { nomeCompleto: 'Jonny Chaparini', dia: 9, mes: 1, anos: 55 },
  { nomeCompleto: 'Marcelo José Ataídes dos Reis', dia: 24, mes: 1, anos: 47 },
  { nomeCompleto: 'Marcelo Antônio Vieira Silva Rosado', dia: 1, mes: 2, anos: 45 },
  { nomeCompleto: 'Cristiano Martins Ferreira e Silva', dia: 1, mes: 2, anos: 49 },
  { nomeCompleto: 'Raul Frederice de Camargo', dia: 9, mes: 2, anos: 46 },
  { nomeCompleto: 'Fabrício Muraro Novais', dia: 19, mes: 2, anos: 51 },
  { nomeCompleto: 'Eduardo Pereira Ribeiro', dia: 27, mes: 2, anos: 54 },
  { nomeCompleto: 'Adalberto José da Silva', dia: 5, mes: 3, anos: 66 },
  { nomeCompleto: 'Célio Fernando de Paula', dia: 6, mes: 3, anos: 50 },
  { nomeCompleto: 'Luís Eduardo Monteiro Lima', dia: 8, mes: 3, anos: 39 },
  { nomeCompleto: 'Sebastião Cirilo de Melo', dia: 15, mes: 3, anos: 84 },
  { nomeCompleto: 'Rafael Camargos Lemes', dia: 17, mes: 3, anos: 43 },
  { nomeCompleto: 'Joaquim Lino Suarte Neto', dia: 28, mes: 3, anos: 61 },
  { nomeCompleto: 'Jean Marc Nacife', dia: 1, mes: 4, anos: 53 },
  { nomeCompleto: 'Josivan Gonçalves Paiva Carmo', dia: 2, mes: 4, anos: 36 },
  { nomeCompleto: 'Jefferson Limonge de Souza', dia: 6, mes: 4, anos: 53 },
  { nomeCompleto: 'Ricardo Abou Rjeili', dia: 7, mes: 4, anos: 49 },
  { nomeCompleto: 'Leonardo Vieira Campos', dia: 7, mes: 4, anos: 46 },
  { nomeCompleto: 'Vailtom Ferreira de Morais', dia: 9, mes: 4, anos: 50 },
  { nomeCompleto: 'João Batista Alves', dia: 21, mes: 4, anos: 75 },
  { nomeCompleto: 'Raul Francisco de Souza Silva', dia: 1, mes: 5, anos: 36 },
  { nomeCompleto: 'Irumuara Interaminense Uliana', dia: 2, mes: 5, anos: 66 },
  { nomeCompleto: 'Arícío Vieira da Silva Júnior', dia: 11, mes: 5, anos: 35 },
  { nomeCompleto: 'Anisio Corrêa da Rocha', dia: 13, mes: 5, anos: 63 },
  { nomeCompleto: 'Dino Moraes de Sousa', dia: 21, mes: 5, anos: 61 },
  { nomeCompleto: 'Abrilino Antônio Schmidt', dia: 25, mes: 5, anos: 61 },
  { nomeCompleto: 'Lucivaldo Tavares Medeiros', dia: 26, mes: 5, anos: 60 },
  { nomeCompleto: 'Kennedy de Araujo Barbosa', dia: 4, mes: 6, anos: 57 },
  { nomeCompleto: 'João Mário Vieira de Paula e Silva', dia: 11, mes: 6, anos: 43 },
  { nomeCompleto: 'Vanderlan dos Santos de Lima Junior', dia: 20, mes: 6, anos: 45 },
  { nomeCompleto: 'Timóteo David Marcelino de Oliveira', dia: 27, mes: 6, anos: 53 },
  { nomeCompleto: 'Bruno Cleyton da Silva Barros', dia: 11, mes: 7, anos: 48 },
  { nomeCompleto: 'Giovanny Duarte Silva', dia: 15, mes: 7, anos: 40 },
  { nomeCompleto: 'Evando Carmo Peres', dia: 16, mes: 7, anos: 58 },
  { nomeCompleto: 'Ricardo Hahimoto de Menezes', dia: 22, mes: 7, anos: 51 },
  { nomeCompleto: 'Orlando Bernardes da Silveira', dia: 30, mes: 7, anos: 74 },
  { nomeCompleto: 'Rodrigo Sebastião Cruvinel Cabral', dia: 31, mes: 7, anos: 50 },
  { nomeCompleto: 'Arícío Vieira da Silva', dia: 1, mes: 8, anos: 55 },
  { nomeCompleto: 'Gabriel Alves Oliveira', dia: 8, mes: 8, anos: 38 },
  { nomeCompleto: 'Airton Vieira da Silva', dia: 13, mes: 8, anos: 64 },
  { nomeCompleto: 'Henrique Antônio de Morais', dia: 16, mes: 8, anos: 57 },
  { nomeCompleto: 'Elexandre Cezar Rossignolo', dia: 25, mes: 8, anos: 54 },
  { nomeCompleto: 'Sergio Ferreira dos Santos', dia: 2, mes: 9, anos: 57 },
  { nomeCompleto: 'Osvaldo Soerger', dia: 6, mes: 9, anos: 53 },
  { nomeCompleto: 'Gustavo César Minelli Martins', dia: 10, mes: 9, anos: 46 },
  { nomeCompleto: 'Pedro Velasco Júnior', dia: 13, mes: 9, anos: 68 },
  { nomeCompleto: 'Fernando Rodrigues de Sousa', dia: 13, mes: 9, anos: 50 },
  { nomeCompleto: 'Antônio Ricardo Alves Padilha', dia: 22, mes: 9, anos: 62 },
  { nomeCompleto: 'Higor Alexsander Mendonça Ferreira', dia: 24, mes: 9, anos: 38 },
  { nomeCompleto: 'Fernando Luiz de Souza Prado', dia: 24, mes: 9, anos: 42 },
  { nomeCompleto: 'Daniel de Albuquerque Pinheiro', dia: 27, mes: 9, anos: 49 },
  { nomeCompleto: 'Anderson Lopes Pereira', dia: 29, mes: 9, anos: 41 },
  { nomeCompleto: 'José Edward Barberato', dia: 29, mes: 9, anos: 49 },
  { nomeCompleto: 'Fernando Veríssimo', dia: 8, mes: 10, anos: 58 },
  { nomeCompleto: 'Marcos Aurélio Silveira Lima', dia: 10, mes: 10, anos: 51 },
  { nomeCompleto: 'Bruno Langoni Salgado', dia: 26, mes: 10, anos: 48 },
  { nomeCompleto: 'Gilberto Campos Guimarães Filho', dia: 8, mes: 11, anos: 49 },
  { nomeCompleto: 'Gilson Borges Mendonça', dia: 16, mes: 11, anos: 54 },
  { nomeCompleto: 'Daniedson Dayves Barbosa', dia: 16, mes: 11, anos: 47 },
  { nomeCompleto: 'Fabricio Diniz Vasconcelos', dia: 18, mes: 11, anos: 49 },
  { nomeCompleto: 'Benjamim José Pinto de Oliveira', dia: 18, mes: 11, anos: 61 },
  { nomeCompleto: 'Edson Donisetti Quinelli', dia: 19, mes: 11, anos: 60 },
  { nomeCompleto: 'Geraldo Pereira de Freitas', dia: 21, mes: 11, anos: 73 },
  { nomeCompleto: 'Marcelo França dos Santos', dia: 22, mes: 11, anos: 27 },
  { nomeCompleto: 'Benedito Cesar Rodero', dia: 25, mes: 11, anos: 65 },
  { nomeCompleto: 'Djan Barbosa de Freitas', dia: 29, mes: 11, anos: 44 },
  { nomeCompleto: 'Mayko Roberto Damasceno Souza', dia: 1, mes: 12, anos: 42 },
  { nomeCompleto: 'Leopoldo de Arruda Lima', dia: 2, mes: 12, anos: 41 },
  { nomeCompleto: 'Parisi Mario Vittório', dia: 6, mes: 12, anos: 56 },
  { nomeCompleto: 'Carlos Conceição Ferreira', dia: 8, mes: 12, anos: 44 },
  { nomeCompleto: 'Bruno Cesar Silva Pereira', dia: 8, mes: 12, anos: 39 },
  { nomeCompleto: 'Giovani Bastos de Miranda', dia: 8, mes: 12, anos: 48 },
  { nomeCompleto: 'Luis Antônio Anacleto Brasileiro', dia: 10, mes: 12, anos: 49 },
  { nomeCompleto: 'Odílio Silva de Paiva Júnior', dia: 19, mes: 12, anos: 51 },
  { nomeCompleto: 'Sebastião Lázaro Pereira', dia: 21, mes: 12, anos: 62 },
  { nomeCompleto: 'Vinícius Bozzolan de Lima', dia: 26, mes: 12, anos: 48 },
  { nomeCompleto: 'Mário Mendes Leão Neto', dia: 27, mes: 12, anos: 52 },
];

export const IMPORTED_CONJUGES: ImportedSpouseBirthday[] = [
  { irmaoNome: 'Antônio Ricardo Alves Padilha', conjugeNome: 'Sandra Cabral Peres Padilha', dia: 3, mes: 1 },
  { irmaoNome: 'Sergio Ferreira dos Santos', conjugeNome: 'Paula Rosana Monteiro Ribeiro dos Santos', dia: 7, mes: 1 },
  { irmaoNome: 'Orlando Bernardes da Silveira', conjugeNome: 'Eleuza Moreira Silva Bernardes', dia: 8, mes: 1 },
  { irmaoNome: 'Irumuara Interaminense Uliana', conjugeNome: 'Dirce Martins Uliana', dia: 28, mes: 1 },
  { irmaoNome: 'Adalberto José da Silva', conjugeNome: 'Kátia Rufina Furquim Silva', dia: 5, mes: 2 },
  { irmaoNome: 'Henrique Antônio de Morais', conjugeNome: 'Simone Winterfeld de Morais', dia: 11, mes: 2 },
  { irmaoNome: 'Benjamim José Pinto de Oliveira', conjugeNome: 'Eliane Oliveira Carvalho', dia: 19, mes: 2 },
  { irmaoNome: 'Daniel de Albuquerque Pinheiro', conjugeNome: 'Iris Morais Oliveira de A. Pinheiro', dia: 19, mes: 2 },
  { irmaoNome: 'Arícío Vieira da Silva', conjugeNome: 'Carolina Merida', dia: 20, mes: 2 },
  { irmaoNome: 'Bruno Langoni Salgado', conjugeNome: 'Lívia Lislie Ferreira Salgado', dia: 24, mes: 2 },
  { irmaoNome: 'Osvaldo Soerger', conjugeNome: 'Emilhane Mengatto Soerger', dia: 25, mes: 2 },
  { irmaoNome: 'Aldo Luis Silva Pereira', conjugeNome: 'Katiane Lima Silva Pereira', dia: 26, mes: 2 },
  { irmaoNome: 'Kennedy de Araujo Barbosa', conjugeNome: 'Verânia Abadia da Silva de Araújo', dia: 2, mes: 3 },
  { irmaoNome: 'Giovani Bastos de Miranda', conjugeNome: 'Mislene Batista Cardoso', dia: 11, mes: 3 },
  { irmaoNome: 'Luis Antônio Anacleto Brasileiro', conjugeNome: 'Kelly Patrícia Torres Vieira Brasileiro', dia: 18, mes: 3 },
  { irmaoNome: 'Ricardo Abou Rjeili', conjugeNome: 'Edineia Araújo Lopes', dia: 20, mes: 3 },
  { irmaoNome: 'Marcos Aurélio Silveira Lima', conjugeNome: 'Keila Valeriana da Silva Lima', dia: 23, mes: 3 },
  { irmaoNome: 'Elexandre Cezar Rossignolo', conjugeNome: 'Juliana Leão Santa Cruz Rossignolo', dia: 27, mes: 3 },
  { irmaoNome: 'Vanderlan dos Santos de Lima Junior', conjugeNome: 'Viviane de Paula Teixeira Lima', dia: 8, mes: 4 },
  { irmaoNome: 'Vinícius Bozzolan de Lima', conjugeNome: 'Roberta Munari Ceribelli', dia: 10, mes: 4 },
  { irmaoNome: 'Vailtom Ferreira de Morais', conjugeNome: 'Letícia Moreira Bernardes', dia: 10, mes: 4 },
  { irmaoNome: 'Jefferson Limonge de Souza', conjugeNome: 'Tani Melo Fernandes', dia: 30, mes: 4 },
  { irmaoNome: 'Daniedson Dayves Barbosa', conjugeNome: 'Leyza Mara Vasconcelos Lopes', dia: 2, mes: 5 },
  { irmaoNome: 'Dino Moraes de Sousa', conjugeNome: 'Celita de Almeida Moraes', dia: 3, mes: 5 },
  { irmaoNome: 'Edson Donisetti Quinelli', conjugeNome: 'Raquel Aparecida B. Quinelli', dia: 5, mes: 5 },
  { irmaoNome: 'Gilberto Campos Guimarães Filho', conjugeNome: 'Ana Carolina Teixeira Guimarães', dia: 8, mes: 5 },
  { irmaoNome: 'Helton José Chacarosque da Silva', conjugeNome: 'Zenaide Caixeta Rodrigues Chacarosque', dia: 12, mes: 5 },
  { irmaoNome: 'Gabriel Alves Oliveira', conjugeNome: 'Priscilla Cabral de Oliveira', dia: 12, mes: 5 },
  { irmaoNome: 'Gustavo César Minelli Martins', conjugeNome: 'Maria do Carmo Pereira R. M. Martins', dia: 13, mes: 5 },
  { irmaoNome: 'Jonny Chaparini', conjugeNome: 'Elda Martins Chaparini', dia: 4, mes: 6 },
  { irmaoNome: 'Eduardo Pereira Ribeiro', conjugeNome: 'Patrícia Ribeiro Pereira', dia: 7, mes: 6 },
  { irmaoNome: 'Ricardo Hahimoto de Menezes', conjugeNome: 'Renata Negrini Souza Marques de Menezes', dia: 15, mes: 6 },
  { irmaoNome: 'Evando Carmo Peres', conjugeNome: 'Lucilene dos Santos Cruvinel Peres', dia: 19, mes: 6 },
  { irmaoNome: 'Marcelo José Ataídes dos Reis', conjugeNome: 'Rosana Angeline Brucceli Reis', dia: 25, mes: 6 },
  { irmaoNome: 'João Mário Vieira de Paula e Silva', conjugeNome: 'Maristela Borges Martins', dia: 28, mes: 6 },
  { irmaoNome: 'Joaquim Lino Suarte Neto', conjugeNome: 'Jackeline da Silva Moreira Suarte', dia: 2, mes: 7 },
  { irmaoNome: 'Fernando Luiz de Souza Prado', conjugeNome: 'Taís Ceci Terossi', dia: 7, mes: 7 },
  { irmaoNome: 'Pedro Velasco Júnior', conjugeNome: 'Ediane Marques Velasco', dia: 22, mes: 7 },
  { irmaoNome: 'Djan Barbosa de Freitas', conjugeNome: 'Cibelle Tavares de Oliveira Freitas', dia: 24, mes: 7 },
  { irmaoNome: 'Anisio Corrêa da Rocha', conjugeNome: 'Jane Alves Gomes da Rocha', dia: 29, mes: 7 },
  { irmaoNome: 'Gilson Borges Mendonça', conjugeNome: 'Lucineide Borges dos Santos', dia: 13, mes: 8 },
  { irmaoNome: 'Parisi Mario Vittório', conjugeNome: 'Fernanda Dutra Caetano Parisi', dia: 28, mes: 8 },
  { irmaoNome: 'Fernando Rodrigues de Sousa', conjugeNome: 'Rocilde Correia de Oliveira Sousa', dia: 28, mes: 8 },
  { irmaoNome: 'Josivan Gonçalves Paiva Carmo', conjugeNome: 'Laíne Batista Queiroz do Carmo', dia: 29, mes: 8 },
  { irmaoNome: 'Bruno Cleyton da Silva Barros', conjugeNome: 'Pauliany Souza Rodrigues Barros', dia: 2, mes: 9 },
  { irmaoNome: 'João Batista Alves', conjugeNome: 'Maria Candida Cruvinel V. Alves', dia: 4, mes: 9 },
  { irmaoNome: 'Benedito Cesar Rodero', conjugeNome: 'Joerlei de Fátima da Silva Rodero', dia: 7, mes: 9 },
  { irmaoNome: 'Airton Vieira da Silva', conjugeNome: 'Dacira Joana de Oliveira e Silva', dia: 28, mes: 9 },
  { irmaoNome: 'Sebastião Cirilo de Melo', conjugeNome: 'Paula Lúcia Finholdt Leão Melo', dia: 29, mes: 9 },
  { irmaoNome: 'Geraldo Pereira de Freitas', conjugeNome: 'Helemi Oliveira Guimaraes de Freitas', dia: 3, mes: 10 },
  { irmaoNome: 'Mário Mendes Leão Neto', conjugeNome: 'Rafaiane Macedo Guimarâes', dia: 7, mes: 10 },
  { irmaoNome: 'Carlos Conceição Ferreira', conjugeNome: 'Déborah Ferreira Bueno', dia: 8, mes: 10 },
  { irmaoNome: 'Fernando Veríssimo', conjugeNome: 'Lucia Helena Mardegan Veríssimo', dia: 25, mes: 10 },
  { irmaoNome: 'Higor Alexsander Mendonça Ferreira', conjugeNome: 'Ângela Carla Vaz da Silva', dia: 26, mes: 10 },
  { irmaoNome: 'Anderson Lopes Pereira', conjugeNome: 'Carla Cristina Silva de Jesus Lopes', dia: 10, mes: 11 },
  { irmaoNome: 'Jean Marc Nacife', conjugeNome: 'Lindaura Eliane Rincon de Castro', dia: 12, mes: 11 },
  { irmaoNome: 'Abrilino Antônio Schmidt', conjugeNome: 'Nívea Morais de Oliveira Schmidt', dia: 14, mes: 11 },
  { irmaoNome: 'Leonardo Vieira Campos', conjugeNome: 'Taísa Oliveira Alves Campos', dia: 20, mes: 11 },
  { irmaoNome: 'Sebastião Lázaro Pereira', conjugeNome: 'Querli Cristina de Fátima Zanutim Pereira', dia: 22, mes: 11 },
  { irmaoNome: 'Timóteo David Marcelino de Oliveira', conjugeNome: 'Rosenilva Rodrigues Silva Vieira', dia: 23, mes: 11 },
  { irmaoNome: 'Célio Fernando de Paula', conjugeNome: 'Cimone Melo Diamantino de Paula', dia: 25, mes: 11 },
  { irmaoNome: 'Leopoldo de Arruda Lima', conjugeNome: 'Lauriane de Queiroz Arantes', dia: 1, mes: 12 },
  { irmaoNome: 'Cristiano Martins Ferreira e Silva', conjugeNome: 'Evely Aparecida Borges Rodrigues', dia: 8, mes: 12 },
  { irmaoNome: 'Marcelo Antônio Vieira Silva Rosado', conjugeNome: 'Lorena Borges Campos', dia: 12, mes: 12 },
  { irmaoNome: 'Fabricio Diniz Vasconcelos', conjugeNome: 'Luciana Silva Guimaraes Vasconcelos', dia: 12, mes: 12 },
  { irmaoNome: 'Raul Francisco de Souza Silva', conjugeNome: 'Francyelle Rezende Amaral', dia: 18, mes: 12 },
];

export const IMPORTED_FILHOS: ImportedChildBirthday[] = [
  { irmaoNome: 'Marcelo José Ataídes dos Reis', nome: 'Eliza Brucceli Reis', dia: 2, mes: 1 },
  { irmaoNome: 'Carlos Conceição Ferreira', nome: 'Athos Bueno Ferreira', dia: 2, mes: 1 },
  { irmaoNome: 'Fabricio Diniz Vasconcelos', nome: 'Amanda Guimaraes Vasconcelos', dia: 7, mes: 1 },
  { irmaoNome: 'Jonny Chaparini', nome: 'Gustavo Chaparini', dia: 16, mes: 1 },
  { irmaoNome: 'Mário Mendes Leão Neto', nome: 'Letícia Lemos Leão', dia: 17, mes: 1 },
  { irmaoNome: 'João Mário Vieira de Paula e Silva', nome: 'Ana Lara Bonfiglioli Martins', dia: 19, mes: 1 },
  { irmaoNome: 'Dino Moraes de Sousa', nome: 'Daniel Ferreira de Sousa', dia: 25, mes: 1 },
  { irmaoNome: 'Daniedson Dayves Barbosa', nome: 'Manuela Vasconcelos Barbosa', dia: 31, mes: 1 },
  { irmaoNome: 'Raul Francisco de Souza Silva', nome: 'Helena Rezende Souza', dia: 9, mes: 2 },
  { irmaoNome: 'Evando Carmo Peres', nome: 'Joice Peres Cruvinel', dia: 12, mes: 2 },
  { irmaoNome: 'Jonny Chaparini', nome: 'Rafaela Chaparini', dia: 19, mes: 2 },
  { irmaoNome: 'Célio Fernando de Paula', nome: 'Enzo Diamantino de Paula', dia: 22, mes: 2 },
  { irmaoNome: 'Sebastião Cirilo de Melo', nome: 'Julliano Finholdt', dia: 24, mes: 2 },
  { irmaoNome: 'Fernando Rodrigues de Sousa', nome: 'Melissa Rodrigues Oliveira', dia: 26, mes: 2 },
  { irmaoNome: 'Gilberto Campos Guimarães Filho', nome: 'Giovanna Teixeira Guimarães', dia: 9, mes: 3 },
  { irmaoNome: 'José Edward Barberato', nome: 'Heitor do Amaral Barberato', dia: 13, mes: 3 },
  { irmaoNome: 'Joaquim Lino Suarte Neto', nome: 'João Marcos de Melo Moreira Suarte', dia: 16, mes: 3 },
  { irmaoNome: 'Joaquim Lino Suarte Neto', nome: 'Antonio Pedro de Melo Moreira Suart', dia: 20, mes: 3 },
  { irmaoNome: 'Helton José Chacarosque da Silva', nome: 'Júlia Caixeta Rodrigues Chacarosque', dia: 26, mes: 3 },
  { irmaoNome: 'Orlando Bernardes da Silveira', nome: 'Letícia Moreira Bernardes', dia: 10, mes: 4 },
  { irmaoNome: 'Helton José Chacarosque da Silva', nome: 'Laura Caixeta Rodrigues Chacarosque', dia: 10, mes: 4 },
  { irmaoNome: 'Helton José Chacarosque da Silva', nome: 'Joaquim Caixeta Rodrigues Chacarosque', dia: 10, mes: 4 },
  { irmaoNome: 'Anderson Lopes Pereira', nome: 'Kamilly Victoria Lopes Silva', dia: 10, mes: 4 },
  { irmaoNome: 'Orlando Bernardes da Silveira', nome: 'Fernando Moreira Bernardes', dia: 11, mes: 4 },
  { irmaoNome: 'Jefferson Limonge de Souza', nome: 'Larissa Fernandes Limonge', dia: 14, mes: 4 },
  { irmaoNome: 'Fernando Luiz de Souza Prado', nome: 'Isabela Terossi Prado', dia: 15, mes: 4 },
  { irmaoNome: 'Vanderlan dos Santos de Lima Junior', nome: 'Cecília Teixeira Lima', dia: 18, mes: 4 },
  { irmaoNome: 'Edson Donisetti Quinelli', nome: 'Andressa Quinelli', dia: 21, mes: 4 },
  { irmaoNome: 'Gilson Borges Mendonça', nome: 'Bruna Monyque Borges dos Santos Curado', dia: 22, mes: 4 },
  { irmaoNome: 'Bruno Langoni Salgado', nome: 'Luana Ferreira Langoni Salgado', dia: 26, mes: 4 },
  { irmaoNome: 'Adalberto José da Silva', nome: 'Aredanna Furquim Silva', dia: 29, mes: 4 },
  { irmaoNome: 'Arícío Vieira da Silva', nome: 'Raul Francisco Souza Silva', dia: 1, mes: 5 },
  { irmaoNome: 'Ricardo Abou Rjeili', nome: 'Beatriz G. Abou Rjeili', dia: 2, mes: 5 },
  { irmaoNome: 'Djan Barbosa de Freitas', nome: 'Davi Tavares de Oliveira Freitas', dia: 4, mes: 5 },
  { irmaoNome: 'Djan Barbosa de Freitas', nome: 'José Vitor Tavares de Oliveira Freitas', dia: 4, mes: 5 },
  { irmaoNome: 'Osvaldo Soerger', nome: 'Guilherme Henrique Soerger', dia: 8, mes: 5 },
  { irmaoNome: 'Adalberto José da Silva', nome: 'Eduardo Furquim Silva', dia: 9, mes: 5 },
  { irmaoNome: 'João Mário Vieira de Paula e Silva', nome: 'Júlia Bonfiglioli Martins', dia: 9, mes: 5 },
  { irmaoNome: 'Kennedy de Araujo Barbosa', nome: 'Luanna Silva de Araujo', dia: 9, mes: 5 },
  { irmaoNome: 'Fernando Veríssimo', nome: 'Fernanda Veríssimo', dia: 9, mes: 5 },
  { irmaoNome: 'Carlos Conceição Ferreira', nome: 'Esther Bueno Ferreira', dia: 9, mes: 5 },
  { irmaoNome: 'João Batista Alves', nome: 'Santhiago Alves Vieira', dia: 10, mes: 5 },
  { irmaoNome: 'Arícío Vieira da Silva', nome: 'Arícío Vieira da Silva Júnior', dia: 11, mes: 5 },
  { irmaoNome: 'Timóteo David Marcelino de Oliveira', nome: 'Leonardo Rodrigues Silva Vieira', dia: 16, mes: 5 },
  { irmaoNome: 'Anisio Corrêa da Rocha', nome: 'Elisa Gomes da Rocha', dia: 22, mes: 5 },
  { irmaoNome: 'Jefferson Limonge de Souza', nome: 'Mariê Nicolle Borges Limonge de Souza', dia: 23, mes: 5 },
  { irmaoNome: 'Luis Antônio Anacleto Brasileiro', nome: 'Ana Luísa Torres Brasileiro', dia: 1, mes: 6 },
  { irmaoNome: 'Bruno Cleyton da Silva Barros', nome: 'Arthur Souza Barros', dia: 3, mes: 6 },
  { irmaoNome: 'Sergio Ferreira dos Santos', nome: 'Bárbara Meireles Santos', dia: 5, mes: 6 },
  { irmaoNome: 'Eduardo Pereira Ribeiro', nome: 'Lorena Ribeiro Pereira', dia: 7, mes: 6 },
  { irmaoNome: 'Geraldo Pereira de Freitas', nome: 'Leninne Guimaraes Freitas', dia: 10, mes: 6 },
  { irmaoNome: 'Leonardo Vieira Campos', nome: 'Davi Oliveira Campos', dia: 15, mes: 6 },
  { irmaoNome: 'Leopoldo de Arruda Lima', nome: 'Paulo Augusto de Queiroz Lima', dia: 17, mes: 6 },
  { irmaoNome: 'Josivan Gonçalves Paiva Carmo', nome: 'João Miguel Queiroz do Carmo', dia: 17, mes: 6 },
  { irmaoNome: 'Henrique Antônio de Morais', nome: 'José Henrique W. de Morais', dia: 18, mes: 6 },
  { irmaoNome: 'Arícío Vieira da Silva Júnior', nome: 'Júlia Castro Vieira', dia: 23, mes: 6 },
  { irmaoNome: 'Benjamim José Pinto de Oliveira', nome: 'Edward Townssend C. Oliveira', dia: 25, mes: 6 },
  { irmaoNome: 'Timóteo David Marcelino de Oliveira', nome: 'Gabriel David M. F. Oliveira', dia: 27, mes: 6 },
  { irmaoNome: 'Bruno Langoni Salgado', nome: 'Antônio Ferreira Langoni Salgado', dia: 29, mes: 6 },
  { irmaoNome: 'Pedro Velasco Júnior', nome: 'Pedro Velasco Neto', dia: 5, mes: 7 },
  { irmaoNome: 'Mário Mendes Leão Neto', nome: 'Henrique Guimarães Leão', dia: 5, mes: 7 },
  { irmaoNome: 'Osvaldo Soerger', nome: 'Mariana Soerger', dia: 6, mes: 7 },
  { irmaoNome: 'Antônio Ricardo Alves Padilha', nome: 'Ricardo Cruz Padilha', dia: 7, mes: 7 },
  { irmaoNome: 'Kennedy de Araujo Barbosa', nome: 'Luís Felipe da Silva Barbosa', dia: 14, mes: 7 },
  { irmaoNome: 'Leopoldo de Arruda Lima', nome: 'Adélcio Pereira Lima Neto', dia: 21, mes: 7 },
  { irmaoNome: 'Anisio Corrêa da Rocha', nome: 'Clara Gomes da Rocha', dia: 24, mes: 7 },
  { irmaoNome: 'Leonardo Vieira Campos', nome: 'Yasmin Oliveira Campos', dia: 28, mes: 7 },
  { irmaoNome: 'João Batista Alves', nome: 'Santiel Alves Vieira Neto', dia: 31, mes: 7 },
  { irmaoNome: 'Anderson Lopes Pereira', nome: 'Bernardo Lopes Silva', dia: 31, mes: 7 },
  { irmaoNome: 'Gabriel Alves Oliveira', nome: 'Gael Cabral Oliveira', dia: 8, mes: 8 },
  { irmaoNome: 'Irumuara Interaminense Uliana', nome: 'Irumuara Interaminense Uliana Filho', dia: 10, mes: 8 },
  { irmaoNome: 'Evando Carmo Peres', nome: 'Jefferson Peres Cruvinel', dia: 19, mes: 8 },
  { irmaoNome: 'Vailtom Ferreira de Morais', nome: 'Maria Eduarda Moreira Morais', dia: 23, mes: 8 },
  { irmaoNome: 'Lucivaldo Tavares Medeiros', nome: 'Izadora Sabino Medeiros', dia: 24, mes: 8 },
  { irmaoNome: 'Gilberto Campos Guimarães Filho', nome: 'Julia Teixeira Guimarães', dia: 25, mes: 8 },
  { irmaoNome: 'Timóteo David Marcelino de Oliveira', nome: 'Willer Vieira da Silva Filho', dia: 28, mes: 8 },
  { irmaoNome: 'Irumuara Interaminense Uliana', nome: 'Leonardo Martins Uliana', dia: 30, mes: 8 },
  { irmaoNome: 'Jefferson Limonge de Souza', nome: 'Marcus Rogério Borges de Souza', dia: 20, mes: 9 },
  { irmaoNome: 'Mário Mendes Leão Neto', nome: 'Heitor Guimarães Leão', dia: 22, mes: 9 },
  { irmaoNome: 'Lucivaldo Tavares Medeiros', nome: 'Júlya Sabino Medeiros', dia: 23, mes: 9 },
  { irmaoNome: 'Fernando Rodrigues de Sousa', nome: 'Luiza Rodrigues Oliveira', dia: 23, mes: 9 },
  { irmaoNome: 'Daniedson Dayves Barbosa', nome: 'Andressa Vasconcelos Lopes Babosa', dia: 7, mes: 10 },
  { irmaoNome: 'Daniel de Albuquerque Pinheiro', nome: 'Pedro C. de Albuquerque Pinheiro', dia: 15, mes: 10 },
  { irmaoNome: 'Gustavo César Minelli Martins', nome: 'Gustavo César Minelli Martins Júnior', dia: 17, mes: 10 },
  { irmaoNome: 'Fernando Luiz de Souza Prado', nome: 'Sofia Terossi Prado', dia: 19, mes: 10 },
  { irmaoNome: 'Anderson Lopes Pereira', nome: 'Nicolas Lopes Silva', dia: 19, mes: 10 },
  { irmaoNome: 'Ricardo Abou Rjeili', nome: 'Gabriel G. Abou Rjeili', dia: 2, mes: 11 },
  { irmaoNome: 'Eduardo Pereira Ribeiro', nome: 'Flavia Ribeiro Pereira', dia: 3, mes: 11 },
  { irmaoNome: 'Marcelo José Ataídes dos Reis', nome: 'Heitor Brucceli Reis', dia: 5, mes: 11 },
  { irmaoNome: 'João Batista Alves', nome: 'Gustavo Alves Vieira', dia: 13, mes: 11 },
  { irmaoNome: 'Benjamim José Pinto de Oliveira', nome: 'Nathalia Townsen C. Oliveira', dia: 14, mes: 11 },
  { irmaoNome: 'Luis Antônio Anacleto Brasileiro', nome: 'João Pedro Torres Brasileiro', dia: 16, mes: 11 },
  { irmaoNome: 'Gilson Borges Mendonça', nome: 'Gabrielly Caroline Borges dos Santos Freitas', dia: 20, mes: 11 },
  { irmaoNome: 'Fernando Veríssimo', nome: 'Eduardo Guilherme Mardegan Veríssimo', dia: 22, mes: 11 },
  { irmaoNome: 'Vailtom Ferreira de Morais', nome: 'Orlando Bernardes da Silveira Neto', dia: 24, mes: 11 },
  { irmaoNome: 'Daniel de Albuquerque Pinheiro', nome: 'Lucas C. de Albuquerque Pinheiro', dia: 2, mes: 12 },
  { irmaoNome: 'Vinícius Bozzolan de Lima', nome: 'Maria Júlia C. B. de Lima', dia: 3, mes: 12 },
  { irmaoNome: 'João Batista Alves', nome: 'Joao Batista Alves Filho', dia: 4, mes: 12 },
  { irmaoNome: 'Orlando Bernardes da Silveira', nome: 'Rhomulo Moreira Bernardes', dia: 5, mes: 12 },
  { irmaoNome: 'Geraldo Pereira de Freitas', nome: 'Giordanne Guimaraes Freitas', dia: 5, mes: 12 },
  { irmaoNome: 'Dino Moraes de Sousa', nome: 'Eduardo Garcez de Moares', dia: 7, mes: 12 },
  { irmaoNome: 'Arícío Vieira da Silva Júnior', nome: 'João Lucas Castro Vieira', dia: 8, mes: 12 },
  { irmaoNome: 'Vanderlan dos Santos de Lima Junior', nome: 'Helena Teixeira Lima', dia: 10, mes: 12 },
  { irmaoNome: 'Sebastião Cirilo de Melo', nome: 'Walmir Finholdt Melo', dia: 16, mes: 12 },
  { irmaoNome: 'Edson Donisetti Quinelli', nome: 'Larissa Quinelli', dia: 16, mes: 12 },
  { irmaoNome: 'Sergio Ferreira dos Santos', nome: 'Catarina Meireles Santos', dia: 22, mes: 12 },
  { irmaoNome: 'Sebastião Cirilo de Melo', nome: 'Mario Mendes Leão Neto', dia: 27, mes: 12 },
  { irmaoNome: 'Antônio Ricardo Alves Padilha', nome: 'Fernanda Cabral Padilha Bacca', dia: 27, mes: 12 },
  { irmaoNome: 'Bruno Cesar Silva Pereira', nome: 'Bia Lovatto Pereira', dia: 28, mes: 12 },
];
