import type { DemolayRosterRow } from './demolay-roster.types';

/**
 * Nominata do Capítulo DeMolay Rio Verde n.º 350 (GO), fornecida pela
 * Administração — base da importação única disparada pelo Administrador
 * em `/admin/pessoas/paramaconicas/[entityId]/importar-demolay-rio-verde-350`.
 * `status` é a classificação de situação do próprio DeMolay
 * (Regular/Irregular/Sênior/Consultor/Inativo/Falecido) — ver
 * `demolay-roster.types.ts`. Ainda não há cruzamento com `Member` (Irmãos
 * já cadastrados na VL6): todo integrante nasce aqui como corpo próprio da
 * entidade, mesmo quem também é Maçom — o vínculo pessoal ficará pra uma
 * etapa seguinte, quando o Administrador levantar quem é quem.
 */
export const DEMOLAY_RIO_VERDE_350_ROSTER: DemolayRosterRow[] = [
  { nomeCompleto: 'Abilio Barbosa Andrade', idMatricula: '87698', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Adelcio Pereira Lima Neto', idMatricula: '129220', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Ademir Pires da Silva Filho', idMatricula: '26723', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Adjackson Arian de Oliveira', idMatricula: '13950', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Alaor Cabral de Melo Neto', idMatricula: '30090', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Aluisio Pancrácio', idMatricula: '54633', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Amilton de Souza Conceição', idMatricula: '105467', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Andre Marques Teixeira', idMatricula: '13317', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Antonio Teles Neto', idMatricula: '9042', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Aricio Vieira da Silva Junior', idMatricula: '9041', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Arthur Chmiel de Moraes', idMatricula: '146249', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Arthur dos Santos Paeze', idMatricula: '109492', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Arthur Leão Jayme', idMatricula: '150747', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Arthur Mendes Antunes', idMatricula: '9034', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Arthur Rodarte Andrade Zanola', idMatricula: '118646', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Arthur Souza Barros', idMatricula: '113962', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Artur Garcia de Carvalho', idMatricula: '140671', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Augusto Ferreira Rezende', idMatricula: '37406', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Augusto Silva Souza Henrique', idMatricula: '146250', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Bacus de Oliveira Nahime', idMatricula: '153718', cargoOriginal: 'Consultor', status: 'Consultor' },
  { nomeCompleto: 'Bruno Alves Faria', idMatricula: '9043', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Bruno Ananias Santos', idMatricula: '39393', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Bruno Cesar Rodero', idMatricula: '9030', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Bruno Langoni Salgado', idMatricula: '72654', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Bruno Lemos Lourenço', idMatricula: '63357', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Bruno Taveira Aernoudts', idMatricula: '45317', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Byron Proto Portilho', idMatricula: '13951', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Caio Victor Souza Silva', idMatricula: '13952', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Carlos Daniel Costa de Medeiros', idMatricula: '80952', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Carlos Ferreira Rios', idMatricula: '110491', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Clailton Ferreira Borges Filho', idMatricula: '71013', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Daniel Bruno Ascari', idMatricula: '72963', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Dannilo Ribeiro Proto Filho', idMatricula: '87692', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Danyllo Proto Soares', idMatricula: '10125', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Davi Lucas Gonçalves Nahime', idMatricula: '140674', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'David Marques Critovao Neto', idMatricula: '26709', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Dário da Cunha Dóro', idMatricula: '6666', cargoOriginal: 'Ex-Membro', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Délio Neto Duarte Melo', idMatricula: '87693', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Diogo Leão Campos', idMatricula: '47498', cargoOriginal: 'Ex-Membro', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Djan Goulart Morais Filho', idMatricula: '118651', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Eduardo Barros Bernardes de Moraes', idMatricula: '33264', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Eduardo Faria Campos', idMatricula: '82043', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Eduardo Furquim Silva', idMatricula: '9032', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Eduardo Teixeira Peres Filho', idMatricula: '35027', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Edward Townsend Carvalho de Oliveira', idMatricula: '39395', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Egberto Toshio Saito', idMatricula: '3836', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Elismar Rodrigues dos Santos', idMatricula: '63359', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Estevão Tiago Nunes Fonseca', idMatricula: '140672', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Eurípedes Antônio dos Santos', idMatricula: '143420', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Everson Alves da Cruz', idMatricula: '48910', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Fábio Carvalho Sanches da Silva', idMatricula: '3837', cargoOriginal: 'Consultor', status: 'Consultor' },
  { nomeCompleto: 'Fábio Lopes Fernandes', idMatricula: '51422', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Felipe Carrion Prado', idMatricula: '150748', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Felipe Carvalho de Brito', idMatricula: '21164', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Felipe Santos Pereira Jaime', idMatricula: '80950', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Felipe Santos Saito', idMatricula: '13953', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Fernando Guimarães Melo', idMatricula: '54634', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Fernando Henrique de Andrade', idMatricula: '21158', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Fernando Luiz de Souza Prado', idMatricula: '46531', cargoOriginal: 'Consultor', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Filippo Giuseppe Parisi', idMatricula: '45313', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Flávio Amorim Chagas', idMatricula: '71015', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Flávio Raimundo Borges', idMatricula: '131450', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Francisco Ribeiro Borges', idMatricula: '63356', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Frederick Khalil Karam', idMatricula: '3422', cargoOriginal: 'PCC', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Gabriel Bonifacio de Sousa', idMatricula: '124835', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Gabriel Campos Araújo Mendes', idMatricula: '61284', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gabriel David Marcelino Oliveira', idMatricula: '109491', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Gabriel de Freitas Braganholo', idMatricula: '113966', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Gabriel Garcia Pavan', idMatricula: '48914', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gabriel Henrique Silva Rohrer Ribeiro', idMatricula: '80951', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gabriel Moraes de Souza', idMatricula: '35028', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gabriel Ribeiro Leão Barroso', idMatricula: '29031', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gabriel Satake Koyama', idMatricula: '61285', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gabriel Scherer Schewning', idMatricula: '13319', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gerson Caetano Almeida Póvoa Dutra', idMatricula: '78445', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Guilherme Alves Santos Cabral', idMatricula: '86733', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Guilherme Calixto Peres', idMatricula: '87697', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Guilherme Franco Santos', idMatricula: '134754', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Guilherme Gonçalves Machado Figueiredo', idMatricula: '48915', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Guilherme Guimarães Costa', idMatricula: '35026', cargoOriginal: null, status: 'Sênior/Consultor' },
  { nomeCompleto: 'Guilherme Luis Azevedo Ruggiero', idMatricula: '102513', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Guilherme Paaz Pinto', idMatricula: '13320', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Guilherme Triches', idMatricula: '13954', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gustavo César Minelli Martins', idMatricula: '3838', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Gustavo César Minelli Martins Junior', idMatricula: '37407', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gustavo Ferreira', idMatricula: '45319', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Gustavo Gonçalves Couto', idMatricula: '42777', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Gustavo Henrique Silva dos Santos', idMatricula: '42781', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gustavo Paiva Caetano', idMatricula: '23684', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Gustavo Santos Bueno de Oliveira', idMatricula: '26752', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Hamilton Aparecido Lopes da Silva', idMatricula: '102512', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Heitor Romano Oliveira', idMatricula: '109495', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Henrico Gonçalves Ferreira', idMatricula: '140673', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Henrique Hiroto Naoe', idMatricula: '51425', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Henrique Machado Borges', idMatricula: '71014', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Henrique Santos Braz', idMatricula: '13955', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Henry Hideki Naoe', idMatricula: '82044', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Higor Alexsander Mendonça Ferreira', idMatricula: '6255', cargoOriginal: 'Ex-Membro', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Higor Rodrigues de Paula', idMatricula: '86738', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Hugo Alves Fernandes', idMatricula: '86739', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Hyago Robert Vaz Souza', idMatricula: '109489', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Ian Santos Garcia', idMatricula: '87695', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Igor Kioshi Hatisuka Marani', idMatricula: '42779', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Irumuara Interaminense Uliana', idMatricula: '3839', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Irumuara Interaminense Uliana Filho', idMatricula: '27708', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Ives Araújo Maldonado', idMatricula: '84344', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Jackson Bueno Boldrin', idMatricula: '23938', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Jhosef Kennedy Lima Dias de Oliveira', idMatricula: '45310', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Joao de Oliveira Prudente', idMatricula: '23936', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'João de Oliveira Damasceno Vasconcelos', idMatricula: '109493', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'João Marcus Paulino Ribeiro', idMatricula: '35025', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'João Pedro Cabral Leão', idMatricula: '33265', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'João Pedro Góis Araújo', idMatricula: '113963', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'João Pedro Sanches Barbosa', idMatricula: '37404', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'João Pedro Valeriano Lima', idMatricula: '42783', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'João Victor Lemos de Oliveira', idMatricula: '87694', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Johann Mortiz Marciano', idMatricula: '105465', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Jorge Augusto Guimaraes Rodrigues', idMatricula: '9031', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'José Henrique Winterfeld de Morais', idMatricula: '71016', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Josivan Gonçalves Paiva Carmo', idMatricula: '105463', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Juliano Rodrigues Lima', idMatricula: '102511', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Jurandir Bessa dos Santos Neto', idMatricula: '37408', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Júlio Varandas Pancracio', idMatricula: '42782', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Leandro Angel Gasques Rodrigues', idMatricula: '105466', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Leandro Rezende Souza Junior', idMatricula: '23937', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Leandro Ribeiro Costa', idMatricula: '102510', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Leonardo Rodrigues', idMatricula: '13956', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Leonardo Rodrigues Silva Vieira', idMatricula: '80953', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Leonardo Vieira Campos', idMatricula: '66047', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Leone da Cunha Doro', idMatricula: '9038', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Leopoldo de Arruda Lima', idMatricula: '153719', cargoOriginal: 'Consultor Org', status: 'Consultor' },
  { nomeCompleto: 'Lessandro Paiva Martins', idMatricula: '53409', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Lucas Bernazzolli de Assis', idMatricula: '26753', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Costa Cruvinel', idMatricula: '48912', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Dangone Pereira', idMatricula: '45314', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Elias Castelli', idMatricula: '87696', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Ferreira Rozan', idMatricula: '150749', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Fonseca Campos Martins', idMatricula: '42776', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Furtado Siqueira de Souza', idMatricula: '45315', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Lucas Gabriel da Silva Dantas', idMatricula: '113964', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Magno Sousa Bernardo', idMatricula: '80834', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Mendes Pereira', idMatricula: '26708', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Lucas Otaviano de Oliveira', idMatricula: '13318', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Rezende de Oliveira', idMatricula: '21161', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Lucas Rodrigues Martins Cardoso', idMatricula: '33266', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Luciano Mendes Gomes Filho', idMatricula: '109496', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Lucio Varandas Pancracio', idMatricula: '45318', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Luis Alberto de Bortoli', idMatricula: '53412', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Luis Eduardo Monteiro Lima', idMatricula: '9039', cargoOriginal: 'Ex-Membro', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Luiz Gustavo Gouveia Morais Silva', idMatricula: '118648', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Luís Otávio Ribeiro', idMatricula: '150750', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Luíz Gustavo Silva Santos', idMatricula: '118650', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Marcelo José Ataídes dos Reis', idMatricula: '52223', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Marcio Antonio Paraguassu de Oliveira', idMatricula: '51424', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Marco Antonio Aires Cruvinel Neto', idMatricula: '118647', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Marco Antonio Silva Santos', idMatricula: '37409', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Marcone Ferreira da Silva', idMatricula: '109487', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Marcos Augusto Messias Filho', idMatricula: '48911', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Marcos Aurélio Silveira Lima', idMatricula: '63358', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Marcos Felipe Ratke', idMatricula: '53411', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Marcos Flávio Fabiano Januário da Silva', idMatricula: '58543', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Marcos Flávio França Mendes', idMatricula: '86633', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Marcos Renato Moraes da Silva', idMatricula: '86737', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Mateus Quirino Batista', idMatricula: '26990', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Mateus Scherer Schwening', idMatricula: '13957', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Matheus Alves Santos', idMatricula: '26710', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Matheus Cardoso Araújo', idMatricula: '109494', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Matheus Danielewz', idMatricula: '21160', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Matheus Maia Teixeira', idMatricula: '23940', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Maurício Hernandez', idMatricula: '53410', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Miguel Jacob Gusati', idMatricula: '134752', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Miguel Moni Guerra Cunha da Câmara', idMatricula: '42778', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Murilo Mendes Antunes', idMatricula: '9035', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Natalicio de Castro Sabino Neto', idMatricula: '45311', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Nelson de Assis Caetano Junior', idMatricula: '37410', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Nicolas Silva França Teixeira', idMatricula: '150753', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Otávio Daniel Lopes da Silva', idMatricula: '146251', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Parisi Mario Vittorio', idMatricula: '54635', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Paulo Chavaglia Filho', idMatricula: '48916', cargoOriginal: 'Ex-Membro', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Paulo Henrique Portilho Cruvinel de Souza', idMatricula: '37405', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Paulo Sergio Rodrigues', idMatricula: '105464', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Paulo Vitor Lima', idMatricula: '13958', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Afonso de Azevedo', idMatricula: '67017', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Appollonio Neto', idMatricula: '30089', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Arthur de Azevedo', idMatricula: '13959', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Augusto Marques Rizzi', idMatricula: '42784', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Castro e Silva', idMatricula: '113967', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Henrique Alves Melo', idMatricula: '78446', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Henrique Lima', idMatricula: '9033', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Henrique Ribeiro Chaves', idMatricula: '150751', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Henrique Segatt', idMatricula: '57440', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Pedro Leão Cabral Sanches', idMatricula: '113968', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Pedro Lucas Cruvinel Martins Cabral', idMatricula: '124834', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Pedro Marques Freitas Lima Filho', idMatricula: '45312', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Martins do Valle', idMatricula: '42780', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Rodrigues de Freitas', idMatricula: '30091', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Pedro Souza Gomes', idMatricula: '118649', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Pedro Velasco Neto', idMatricula: '42786', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Pedro Venâncio Alves Bortolo', idMatricula: '113965', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Rafael Campos Araújo Mendes', idMatricula: '61283', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Rafael Diogo Pereira Souza', idMatricula: '29030', cargoOriginal: 'Ex-Membro', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Rafael Henrique Silva', idMatricula: '21163', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Raul Francisco de Souza Silva', idMatricula: '9040', cargoOriginal: 'Ex-Membro', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Regis Rocha Rodrigues Resende', idMatricula: '82045', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Renan Thielke', idMatricula: '9036', cargoOriginal: 'Ex-Membro', status: 'Irregular' },
  { nomeCompleto: 'Régio de Faria Paiva Filho', idMatricula: '134751', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Ricardo Abou Rjeili', idMatricula: '72653', cargoOriginal: 'Ex-Membro', status: 'Sênior/Consultor' },
  { nomeCompleto: 'Ricardo Leao Carmo', idMatricula: '23941', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Richard Castro Rodrigues', idMatricula: '134755', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Rodrigo Pereira Freitas', idMatricula: '13960', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Rodrigo Silveira Soares', idMatricula: '86735', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Rondinelli dos Reis Rezende', idMatricula: '3840', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Roque Matheus Gomes Monteiro de Mello', idMatricula: '125017', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Salomão José do Nascimento Barros', idMatricula: '86734', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Samuel Gomes Timóteo Lima', idMatricula: '150752', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Thiago Souza Gomes', idMatricula: '71012', cargoOriginal: null, status: 'Falecido' },
  { nomeCompleto: 'Thiago Vieira Alves', idMatricula: '86736', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Thiago Vieira Freitas', idMatricula: '57441', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Timóteo David Marcelino de Oliveira', idMatricula: '102509', cargoOriginal: 'Ex-Membro', status: 'Consultor' },
  { nomeCompleto: 'Tulio Travain Paim', idMatricula: '45316', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Valdir Machado de Souza Junior', idMatricula: '12933', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Valfredo Bezerra de Brito Neto', idMatricula: '67777', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Vander Zaltu Barros Filho', idMatricula: '21162', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Vicente Augusto Chiodi', idMatricula: '39394', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Victor Diniz Andre', idMatricula: '21159', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Victor Hugo Costa Schervenski', idMatricula: '87699', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Victor Julio Almeida Silva', idMatricula: '37411', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Vinicio da Cunha Doro', idMatricula: '9037', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Vinicius Oliveira Cardoso', idMatricula: '39396', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Vinicius Souza Macedo', idMatricula: '71011', cargoOriginal: null, status: 'Inativo' },
  { nomeCompleto: 'Vinicius Triches', idMatricula: '13961', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Vinícius Lima Nunes', idMatricula: '42785', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Vitor Hugo Guimarães Losi', idMatricula: '109488', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Vitor Miranda', idMatricula: '134753', cargoOriginal: null, status: 'Regular' },
  { nomeCompleto: 'Vitor Rodrigues Silva', idMatricula: '146252', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Vítor Hugo Silva da Rocha', idMatricula: '67137', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Wayner José de Sousa Filho', idMatricula: '59289', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Wellington Aires de Andrade', idMatricula: '43807', cargoOriginal: null, status: 'Sênior' },
  { nomeCompleto: 'Willer Vieira da Silva Filho', idMatricula: '109490', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Willian Marcelino Carvalho', idMatricula: '35456', cargoOriginal: 'Ex-Membro', status: 'Irregular' },
  { nomeCompleto: 'Yuri Campos Nunes Silva', idMatricula: '23939', cargoOriginal: null, status: 'Irregular' },
  { nomeCompleto: 'Yuri Rafael Faria de Oliveira', idMatricula: '86740', cargoOriginal: null, status: 'Inativo' },
];
