import type { PermissionKey } from '@vl6/shared';
export interface AdminTool {
  href: string;
  label: string;
  group: string;
  permissions: PermissionKey[];
}
/** Apenas destinos de ferramentas: nunca indexa registros pessoais, cartas ou segredos. */
export const ADMIN_TOOLS: AdminTool[] = [
  {
    href: '/admin/acervo/arquivos',
    label: 'Documentos',
    group: 'Acervo e Biblioteca',
    permissions: ['file:read'],
  },
  {
    href: '/admin/acervo/biblioteca/baixas/ocorrencias',
    label: 'Ocorrências de exemplares · Biblioteca',
    group: 'Acervo e Biblioteca',
    permissions: ['libraryItem:manage'],
  },
  {
    href: '/admin/acervo/biblioteca/baixas',
    label: 'Baixas da Biblioteca · Biblioteca',
    group: 'Acervo e Biblioteca',
    permissions: ['libraryItem:manage'],
  },
  {
    href: '/admin/acervo/biblioteca/downloads',
    label: 'Relatório de downloads · Biblioteca',
    group: 'Acervo e Biblioteca',
    permissions: ['libraryItem:manage'],
  },
  {
    href: '/admin/acervo/biblioteca/emprestimo-presencial',
    label: 'Empréstimo presencial',
    group: 'Acervo e Biblioteca',
    permissions: ['libraryItem:manage'],
  },
  {
    href: '/admin/acervo/biblioteca/emprestimos',
    label: 'Fila de empréstimos',
    group: 'Acervo e Biblioteca',
    permissions: ['libraryItem:manage'],
  },
  {
    href: '/admin/acervo/biblioteca/estantes',
    label: 'Estantes',
    group: 'Acervo e Biblioteca',
    permissions: ['libraryItem:manage'],
  },
  {
    href: '/admin/acervo/biblioteca/etiquetas',
    label: 'Etiquetas QR',
    group: 'Acervo e Biblioteca',
    permissions: ['libraryItem:manage'],
  },
  {
    href: '/admin/acervo/biblioteca/lixeira',
    label: 'Lixeira · Biblioteca',
    group: 'Acervo e Biblioteca',
    permissions: ['libraryItem:manage'],
  },
  {
    href: '/admin/acervo/biblioteca',
    label: 'Catálogo da Biblioteca',
    group: 'Acervo e Biblioteca',
    permissions: ['libraryItem:read'],
  },
  {
    href: '/admin/acervo/catalogacao',
    label: 'Catalogação',
    group: 'Acervo e Biblioteca',
    permissions: ['archiveCatalog:read'],
  },
  {
    href: '/admin/acervo/colecoes',
    label: 'Coleções',
    group: 'Acervo e Biblioteca',
    permissions: ['archiveCollection:read'],
  },
  {
    href: '/admin/acervo/contribuicoes',
    label: 'Contribuicoes',
    group: 'Acervo e Biblioteca',
    permissions: ['archiveContribution:manage'],
  },
  {
    href: '/admin/acervo/duplicidade',
    label: 'Conferência de mídias duplicadas',
    group: 'Acervo e Biblioteca',
    permissions: ['archiveMedia:manage'],
  },
  {
    href: '/admin/acervo/elevacao-migracao',
    label: 'Reconciliação de elevações',
    group: 'Manutenção',
    permissions: ['member:manage'],
  },
  {
    href: '/admin/acervo/exaltacao-migracao',
    label: 'Reconciliação de exaltações',
    group: 'Manutenção',
    permissions: ['member:manage'],
  },
  {
    href: '/admin/acervo/exposicoes',
    label: 'Exposições',
    group: 'Acervo e Biblioteca',
    permissions: ['archiveExhibition:read'],
  },
  {
    href: '/admin/acervo/galeria',
    label: 'Fotografias e vídeos',
    group: 'Acervo e Biblioteca',
    permissions: ['gallery:read'],
  },
  {
    href: '/admin/acervo/iniciacao-migracao',
    label: 'Reconciliação de iniciações',
    group: 'Manutenção',
    permissions: ['member:manage'],
  },
  {
    href: '/admin/acervo/lixeira',
    label: 'Lixeira · Acervo',
    group: 'Acervo e Biblioteca',
    permissions: ['archiveItem:delete'],
  },
  {
    href: '/admin/acervo/metricas',
    label: 'Métricas do Acervo',
    group: 'Acervo e Biblioteca',
    permissions: ['archiveMedia:manage'],
  },
  {
    href: '/admin/acervo/migracao',
    label: 'Migração do Acervo',
    group: 'Manutenção',
    permissions: ['archiveItem:create'],
  },
  {
    href: '/admin/acervo/publicar',
    label: 'Publicação do Acervo',
    group: 'Acervo e Biblioteca',
    permissions: ['archiveItem:create'],
  },
  {
    href: '/admin/acervo/relacoes',
    label: 'Relações do Acervo',
    group: 'Acervo e Biblioteca',
    permissions: ['archiveRelation:read'],
  },
  {
    href: '/admin/comunicacao/modelos',
    label: 'Modelos e artes',
    group: 'Publicações e Agenda',
    permissions: ['communication:manage'],
  },
  {
    href: '/admin/comunicacao',
    label: 'Comunicação',
    group: 'Publicações e Agenda',
    permissions: ['communication:manage'],
  },
  {
    href: '/admin/configuracoes/auditoria',
    label: 'Auditoria',
    group: 'Configurações e Auditoria',
    permissions: ['auditLog:read'],
  },
  {
    href: '/admin/configuracoes/geral',
    label: 'Configurações gerais',
    group: 'Configurações e Auditoria',
    permissions: ['tenant:read'],
  },
  {
    href: '/admin/configuracoes/integracoes',
    label: 'Integrações',
    group: 'Configurações e Auditoria',
    permissions: ['tenant:manage'],
  },
  {
    href: '/admin/configuracoes/termos-e-privacidade',
    label: 'Termos e privacidade',
    group: 'Configurações e Auditoria',
    permissions: ['legalDocument:manage'],
  },
  {
    href: '/admin/conteudo/agenda/classificacao-migracao',
    label: 'Migração de classificação de sessões',
    group: 'Manutenção',
    permissions: ['event:manage'],
  },
  {
    href: '/admin/conteudo/agenda',
    label: 'Agenda',
    group: 'Publicações e Agenda',
    permissions: ['event:read'],
  },
  {
    href: '/admin/conteudo/agenda/revisao',
    label: 'Revisão de sessões',
    group: 'Publicações e Agenda',
    permissions: ['event:manage'],
  },
  {
    href: '/admin/conteudo/avisos',
    label: 'Avisos',
    group: 'Publicações e Agenda',
    permissions: ['announcement:read'],
  },
  {
    href: '/admin/conteudo/frases',
    label: 'Frases',
    group: 'Publicações e Agenda',
    permissions: ['quote:read'],
  },
  {
    href: '/admin/conteudo/links',
    label: 'Links úteis',
    group: 'Publicações e Agenda',
    permissions: ['link:read'],
  },
  {
    href: '/admin/conteudo/noticias/comentarios',
    label: 'Moderação de comentários',
    group: 'Publicações e Agenda',
    permissions: ['news:manage'],
  },
  {
    href: '/admin/conteudo/noticias',
    label: 'Notícias',
    group: 'Publicações e Agenda',
    permissions: ['news:read'],
  },
  {
    href: '/admin/cripta/abertura-individual',
    label: 'Abertura individual',
    group: 'Cripta',
    permissions: ['tenant:manage'],
  },
  {
    href: '/admin/cripta/manutencao',
    label: 'Manutenção da Cripta',
    group: 'Manutenção',
    permissions: ['tenant:manage'],
  },
  {
    href: '/admin/cripta',
    label: 'Cripta',
    group: 'Cripta',
    permissions: ['tenant:manage'],
  },
  {
    href: '/admin/cripta/projetor',
    label: 'Projetor e cerimônias',
    group: 'Cripta',
    permissions: ['tenant:manage'],
  },
  {
    href: '/admin/pessoas/central',
    label: 'Perfis da Central',
    group: 'Pessoas e Loja',
    permissions: ['memberCentral:manage'],
  },
  {
    href: '/admin/pessoas/gestoes/importar-nominata',
    label: 'Importar nominata',
    group: 'Manutenção',
    permissions: ['boardTerm:manage'],
  },
  {
    href: '/admin/pessoas/gestoes',
    label: 'Gestões e nominatas',
    group: 'Pessoas e Loja',
    permissions: ['boardTerm:read'],
  },
  {
    href: '/admin/pessoas/irmaos/duplicados',
    label: 'Revisão de Irmãos duplicados',
    group: 'Pessoas e Loja',
    permissions: ['member:manage'],
  },
  {
    href: '/admin/pessoas/irmaos/importar',
    label: 'Importar Irmãos',
    group: 'Manutenção',
    permissions: ['member:create'],
  },
  {
    href: '/admin/pessoas/irmaos',
    label: 'Irmãos',
    group: 'Pessoas e Loja',
    permissions: ['member:read'],
  },
  {
    href: '/admin/pessoas/irmaos/reconciliar-ativos',
    label: 'Reconciliação de Irmãos ativos',
    group: 'Manutenção',
    permissions: ['member:manage'],
  },
  {
    href: '/admin/pessoas/irmaos/relatorio',
    label: 'Relatório de Irmãos',
    group: 'Pessoas e Loja',
    permissions: ['member:read'],
  },
  {
    href: '/admin/pessoas/loja',
    label: 'Identidade da Loja',
    group: 'Pessoas e Loja',
    permissions: ['branding:read'],
  },
  {
    href: '/admin/pessoas/negocios',
    label: 'Negócios e serviços',
    group: 'Pessoas e Loja',
    permissions: ['memberCentral:manage'],
  },
  {
    href: '/admin/pessoas/paramaconicas/importar-demolay-rio-verde-350',
    label: 'Importação DeMolay Rio Verde',
    group: 'Manutenção',
    permissions: ['paramasonicEntity:manage'],
  },
  {
    href: '/admin/pessoas/paramaconicas',
    label: 'Paramaçônicas',
    group: 'Pessoas e Loja',
    permissions: ['paramasonicEntity:read'],
  },
  {
    href: '/admin/pessoas/permissoes',
    label: 'Papéis e permissões',
    group: 'Pessoas e Loja',
    permissions: ['role:read'],
  },
  {
    href: '/admin/pessoas/situacao-migracao',
    label: 'Migração de situação maçônica',
    group: 'Manutenção',
    permissions: ['member:manage'],
  },
  {
    href: '/admin/pessoas/usuarios',
    label: 'Contas de acesso',
    group: 'Pessoas e Loja',
    permissions: ['user:read'],
  },
  {
    href: '/admin/publicacoes',
    label: 'Planejamento editorial',
    group: 'Publicações e Agenda',
    permissions: [
      'event:read',
      'announcement:read',
      'news:read',
      'communication:manage',
      'archiveItem:create',
    ],
  },
  {
    href: '/admin/conhecimento',
    label: 'Gestão do Conhecimento',
    group: 'Conhecimento',
    permissions: ['knowledge:manage', 'tenant:manage'],
  },
  {
    href: '/admin/conhecimento/revisoes',
    label: 'Revisões e atividades',
    group: 'Conhecimento',
    permissions: ['knowledge:manage', 'tenant:manage'],
  },
  {
    href: '/admin/conhecimento/relatorios',
    label: 'Relatórios autorizados',
    group: 'Conhecimento',
    permissions: ['knowledge:manage', 'tenant:manage'],
  },
  {
    href: '/admin/conteudo/notificacoes/nova',
    label: 'Notificação pessoal',
    group: 'Publicações e Agenda',
    permissions: ['notification:manage'],
  },
  {
    href: '/admin/cripta/demonstracao',
    label: 'Demonstração da Cripta',
    group: 'Manutenção',
    permissions: ['tenant:manage'],
  },
  {
    href: '/admin/cripta/laboratorio',
    label: 'Laboratório da Cripta',
    group: 'Manutenção',
    permissions: ['tenant:manage'],
  },
];
