/**
 * Lista fechada de Irmãos que devem permanecer com Situação "Ativo" e
 * acesso ao Portal — passada pelo Administrador em 2026-09-14 pra
 * reconciliar o cadastro depois de anos de importações/migrações sem
 * revisão de quem ainda está em atividade na Loja. Uso único: alimenta
 * `PreviewActiveMembersReconciliationUseCase`/
 * `ApplyActiveMembersReconciliationUseCase` — não é reaproveitada por
 * nenhum outro fluxo, então fica isolada aqui em vez de virar uma tela de
 * importação genérica.
 */
export const ACTIVE_MEMBERS_RECONCILIATION_LIST: readonly string[] = [
  'Aldo Luis Silva Pereira',
  'Helton José Chacarosque da Silva',
  'Jonny Chaparini',
  'Marcelo José Ataídes dos Reis',
  'Marcelo Antônio Vieira Silva Rosado',
  'Cristiano Martins Ferreira e Silva',
  'Raul Frederice de Camargo',
  'Fabricio Muraro Novais',
  'Eduardo Pereira Ribeiro',
  'Adalberto José da Silva',
  'Célio Fernando de Paula',
  'Luis Eduardo Monteiro Lima',
  'Sebastião Cirilo de Melo',
  'Rafael Camargos Lemes',
  'Joaquim Lino Suarte Neto',
  'Jean Marc Nacife',
  'Josivan Gonçalves Paiva Carmo',
  'Jefferson Limonge de Souza',
  'Ricardo Abou Rjeili',
  'Leonardo Vieira Campos',
  'Vailtom Ferreira de Morais',
  'João Batista Alves',
  'Raul Francisco de Souza Silva',
  'Irumuara Interaminense Uliana',
  'Arício Vieira da Silva Júnior',
  'Anisio Corrêa da Rocha',
  'Dino Moraes de Sousa',
  'Abrilino Antônio Schmidt',
  'Lucivaldo Tavares Medeiros',
  'Kennedy de Araujo Barbosa',
  'João Mário Vieira de Paula e Silva',
  'Vanderlan dos Santos de Lima Junior',
  'Timóteo David Marcelino de Oliveira',
  'Bruno Cleyton da Silva Barros',
  'Giovanny Duarte Silva',
  'Evando Carmo Peres',
  'Ricardo Hahimoto de Menezes',
  'Orlando Bernardes da Silveira',
  'Rodrigo Sebastião Cruvinel Cabral',
  'Arício Vieira da Silva',
  'Gabriel Alves Oliveira',
  'Airton Vieira da Silva',
  'Henrique Antônio de Morais',
  'Elexandre Cezar Rossignolo',
  'Sergio Ferreira dos Santos',
  'Osvaldo Soerger',
  'Gustavo César Minelli Martins',
  'Pedro Velasco Júnior',
  'Fernando Rodrigues de Sousa',
  'Antônio Ricardo Alves Padilha',
  'Higor Alexsander Mendonça Ferreira',
  'Fernando Luiz de Souza Prado',
  'Daniel de Albuquerque Pinheiro',
  'Anderson Lopes Pereira',
  'José Edward Barberato',
  'Fernando Veríssimo',
  'Marcos Aurélio Silveira Lima',
  'Bruno Langoni Salgado',
  'Gilberto Campos Guimarães Filho',
  'Gilson Borges Mendonça',
  'Daniedson Dayves Barbosa',
  'Fabricio Diniz Vasconcelos',
  'Benjamin José Pinto de Oliveira',
  'Edson Donisetti Quinelli',
  'Geraldo Pereira de Freitas',
  'Marcelo França dos Santos',
  'Benedito Cesar Rodero',
  'Djan Barbosa de Freitas',
  'Mayko Roberto Damasceno Souza',
  'Leopoldo de Arruda Lima',
  'Parisi Mario Vittório',
  'Carlos Conceição Ferreira',
  'Bruno Cesar Silva Pereira',
  'Giovani Bastos de Miranda',
  'Luis Antônio Anacleto Brasileiro',
  'Odílio Silva de Paiva Júnior',
  'Sebastião Lázaro Pereira',
  'Vinícius Bozzolan de Lima',
  'Mário Mendes Leão Neto',
];
